/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2022.1.2209140739
    Soft IP Version: 1.4.0
    2022 09 14 16:29:05
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module osc0 (hf_out_en_i, hf_clk_out_o, lf_clk_out_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  hf_out_en_i;
    output  hf_clk_out_o;
    output  lf_clk_out_o;
endmodule